stages:
    - test
    - server_config
    - deploy

before_script:
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - mkdir -p ~/.ssh
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$SERVER_PRIVATE_KEY")
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'

test:
    stage: test
    image: amorvan/env_test
    only:
       - _dev
    before_script:
       - php -v
       - composer install
       - composer dump-autoload -o
       - php bin/console --env=test d:d:c
       - php bin/console --env=test d:s:u --force
    script:
       - echo "Functionnal & Unit tests"
       - vendor/bin/phpunit -v

server_config:
    stage: server_config
    image: amorvan/env_test
    only:
        - master
    script:
        - echo 'server configuration in progress'
        - ssh $server_user@$server_host "rm -rf /var/www/html/$PROJECT_NAME/$PROJECT_ENV"
        - ssh $server_user@$server_host "mkdir -p /home/$SERVER_OWNER/www/$PROJECT_NAME/$PROJECT_ENV"
        - ssh $server_user@$server_host "ln -s -f /home/$SERVER_OWNER/www/$PROJECT_NAME/$PROJECT_ENV/ /var/www/html/$PROJECT_NAME"
        - ssh $server_user@$server_host "chown -hR $SERVER_OWNER:users /home/$SERVER_OWNER/www/$PROJECT_NAME/$PROJECT_ENV && chmod -R 777 /home/$SERVER_OWNER/www/$PROJECT_NAME/$PROJECT_ENV"
        - echo 'Projet folder created and configured'
        - scp -r /etc/apache2/sites-available/$PROJECT_NAME-$PROJECT_ENV.conf $server_user@$server_host:/etc/apache2/sites-available/$PROJECT_NAME-$PROJECT_ENV.conf
        - ssh $server_user@$server_host "a2ensite $PROJECT_NAME-$PROJECT_ENV.conf && a2enmod ssl && service apache2 restart"
        - ssh $server_user@$server_host "systemctl status apache2.service"
        - echo 'Project server configuration activated'

deploy:
    stage: deploy
    image: amorvan/env_test
    only:
        - master
    script:
        - echo 'Deployment in progress'
        - scp -r ./* $server_user@$server_host:/home/$SERVER_OWNER/www/$PROJECT_NAME/$PROJECT_ENV
        - ssh $server_user@$server_host "cd /home/$SERVER_OWNER/www/$PROJECT_NAME/$PROJECT_ENV && composer install && composer dump-autoload -o"
        - ssh $server_user@$server_host "rm -rf /home/$SERVER_OWNER/www/$PROJECT_NAME/$PROJECT_ENV/var/cache/*"
        - ssh $server_user@$server_host "systemctl status apache2.service"
        - echo 'Project binaries moved and installed'