imports:
    - { resource: config_dev.yml }

framework:
    test: ~
    session:
        storage_id: session.storage.mock_file
    profiler:
        collect: true

web_profiler:
    toolbar: true
#    intercept_redirects: true

swiftmailer:
    disable_delivery: true
#    transport: "%mailer_transport%"
#    username:  "%mailer_user%"
#    password:  "123456"

doctrine:
    dbal:
        driver: pdo_sqlite
        memory: true
        path: '%kernel.cache_dir%/test.db'
