# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
services:
# Service Mailer
    app.mailer_service:
        class: AppBundle\Services\MailerService
        arguments:
            - '@mailer'
            - '%mail_send_mail_museum%'
            - '%name_contact%'
            - '@templating'
            - '%webdir%'
# Service Contact
    app.contact_service:
        class: AppBundle\Services\ContactService
        arguments:
            - '@form.factory'
            - '@app.mailer_service'
            - '@session'
# Service Price
    app.price_service:
        class: AppBundle\Services\PriceService
        public: false

# Manager
    app.order_manager:
        class: AppBundle\Services\OrderManager
        arguments:
            - '@form.factory'
            - '@doctrine.orm.entity_manager'
            - '@session'
            - '@app.mailer_service'
            - '@app.price_service'
            - '%stripe.token%'
    app.ticket_manager:
        class: AppBundle\Services\TicketManager
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@session'
