# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    recipient_adress: '%adress_contact%'
    recipient_name: '%name_contact%'

services:
# Service Mailer
    app.mailer_service:
        class: AppBundle\Services\MailerService
        arguments:
            - '@mailer'
            - '%recipient_adress%'
            - '%recipient_name%'
            - '@templating'

# Service Contact
    app.contact_service:
        class: AppBundle\Services\ContactService
        arguments:
            - '@form.factory'
            - '@app.mailer_service'